version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - cook_pod
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0' --environment test"
    volumes:
      - .:/cook_pod
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: daae28478850432d72f315cf11c90f84988fb19f156dd917ce6b773c07d79366a33e86274593bf7b48f72933bc90ff59a95bf589a0dca07ae95
      ALLOW_CORS_ORIGIN: http://localhost:3002
    networks:
      - cook_pod
  nginx:
    image: 921126570142.dkr.ecr.us-west-2.amazonaws.com/cook_pod_nginx:latest
    depends_on:
      - web
    environment:
      WORKER_PROCESSES: 2
      WORKER_CONNECTIONS: 1024
      KEEPALIVE_TIMEOUT: 65
      GZIP: "on"
      BACKEND_HOST: 172.24.0.3:3001
      BACKEND_MAX_FAILS: 3
      BACKEND_FAIL_TIMEOUT: 10s
      SERVER_PORT: 80
      LOG_STDOUT: "true"
    ports:
      - "80:80"
    networks:
      - cook_pod
networks:
  cook_pod:
    external: true
